<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>PhiraMp.Plugin.SDK</AssemblyName>
    <RootNamespace>PhiraMp.Plugin.SDK</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhiraMp.Core\PhiraMp.Core.csproj" />
  </ItemGroup>

</Project>
